/**
 * @file PluginSandbox.h
 * @brief Interface for process-level sandboxing of audio plugins.
 */

#pragma once

#include <memory>
#include <string>
#include <vector>

namespace daiw {
namespace plugins {

/**
 * @class PluginSandbox
 * @brief Abstract base class for platform-specific process sandboxing.
 *
 * Part of Phase 1: Audio Engine Core (P1-008).
 * Enables running plugins in separate processes to prevent host crashes.
 */
class PluginSandbox {
public:
  virtual ~PluginSandbox() = default;

  /**
   * Launch a separate process to host a plugin.
   * @param pluginPath Path to the plugin to load.
   * @param ipcPort The port to use for IPC communication.
   * @return True if the process was launched successfully.
   */
  virtual bool launch(const std::string &pluginPath, int ipcPort) = 0;

  /**
   * Terminate the sandboxed process.
   */
  virtual void terminate() = 0;

  /**
   * Check if the sandboxed process is still alive.
   * @return True if the process is running.
   */
  virtual bool isAlive() const = 0;

  /**
   * Get the process ID of the sandboxed process.
   * @return The PID, or -1 if not running.
   */
  virtual int getProcessId() const = 0;

  /**
   * Get any output generated by the sandboxed process.
   * @return The process output.
   */
  virtual std::string getOutput() = 0;

  /**
   * Static factory method to create a platform-specific sandbox instance.
   */
  static std::unique_ptr<PluginSandbox> create();
};

} // namespace plugins
} // namespace daiw
