add_test( [==[TimeSignature operations]==] [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug/penta_tests]==] [==[TimeSignature operations]==]  )
set_tests_properties( [==[TimeSignature operations]==] PROPERTIES WORKING_DIRECTORY [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug]==])
add_test( [==[TimeSignature 3/4]==] [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug/penta_tests]==] [==[TimeSignature 3/4]==]  )
set_tests_properties( [==[TimeSignature 3/4]==] PROPERTIES WORKING_DIRECTORY [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug]==])
add_test( [==[Tempo calculations]==] [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug/penta_tests]==] [==[Tempo calculations]==]  )
set_tests_properties( [==[Tempo calculations]==] PROPERTIES WORKING_DIRECTORY [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug]==])
add_test( [==[GrooveSettings defaults]==] [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug/penta_tests]==] [==[GrooveSettings defaults]==]  )
set_tests_properties( [==[GrooveSettings defaults]==] PROPERTIES WORKING_DIRECTORY [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug]==])
add_test( [==[NoteEvent operations]==] [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug/penta_tests]==] [==[NoteEvent operations]==]  )
set_tests_properties( [==[NoteEvent operations]==] PROPERTIES WORKING_DIRECTORY [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug]==])
add_test( [==[Groove settings ranges]==] [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug/penta_tests]==] [==[Groove settings ranges]==]  )
set_tests_properties( [==[Groove settings ranges]==] PROPERTIES WORKING_DIRECTORY [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug]==])
add_test( [==[MemoryPool basic operations]==] [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug/penta_tests]==] [==[MemoryPool basic operations]==]  )
set_tests_properties( [==[MemoryPool basic operations]==] PROPERTIES WORKING_DIRECTORY [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug]==])
add_test( [==[RingBuffer operations]==] [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug/penta_tests]==] [==[RingBuffer operations]==]  )
set_tests_properties( [==[RingBuffer operations]==] PROPERTIES WORKING_DIRECTORY [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug]==])
add_test( [==[SIMD scale operation]==] [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug/penta_tests]==] [==[SIMD scale operation]==]  )
set_tests_properties( [==[SIMD scale operation]==] PROPERTIES WORKING_DIRECTORY [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug]==])
add_test( [==[SIMD add operation]==] [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug/penta_tests]==] [==[SIMD add operation]==]  )
set_tests_properties( [==[SIMD add operation]==] PROPERTIES WORKING_DIRECTORY [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug]==])
add_test( [==[ScaleDetector RT-safety and detection]==] [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug/penta_tests]==] [==[ScaleDetector RT-safety and detection]==]  )
set_tests_properties( [==[ScaleDetector RT-safety and detection]==] PROPERTIES WORKING_DIRECTORY [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug]==])
add_test( [==[VoiceLeading RT-safety and motion]==] [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug/penta_tests]==] [==[VoiceLeading RT-safety and motion]==]  )
set_tests_properties( [==[VoiceLeading RT-safety and motion]==] PROPERTIES WORKING_DIRECTORY [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug]==])
add_test( [==[OnsetDetector and TempoEstimator]==] [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug/penta_tests]==] [==[OnsetDetector and TempoEstimator]==]  )
set_tests_properties( [==[OnsetDetector and TempoEstimator]==] PROPERTIES WORKING_DIRECTORY [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug]==])
add_test( [==[RhythmQuantizer and Swing]==] [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug/penta_tests]==] [==[RhythmQuantizer and Swing]==]  )
set_tests_properties( [==[RhythmQuantizer and Swing]==] PROPERTIES WORKING_DIRECTORY [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug]==])
add_test( [==[Diagnostics performance and audio]==] [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug/penta_tests]==] [==[Diagnostics performance and audio]==]  )
set_tests_properties( [==[Diagnostics performance and audio]==] PROPERTIES WORKING_DIRECTORY [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug]==])
add_test( [==[OSC RT-safe messaging]==] [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug/penta_tests]==] [==[OSC RT-safe messaging]==]  )
set_tests_properties( [==[OSC RT-safe messaging]==] PROPERTIES WORKING_DIRECTORY [==[/Volumes/Extreme SSD/kelly-project/audio-engine-cpp/build-debug]==])
set( penta_tests_TESTS [==[TimeSignature operations]==] [==[TimeSignature 3/4]==] [==[Tempo calculations]==] [==[GrooveSettings defaults]==] [==[NoteEvent operations]==] [==[Groove settings ranges]==] [==[MemoryPool basic operations]==] [==[RingBuffer operations]==] [==[SIMD scale operation]==] [==[SIMD add operation]==] [==[ScaleDetector RT-safety and detection]==] [==[VoiceLeading RT-safety and motion]==] [==[OnsetDetector and TempoEstimator]==] [==[RhythmQuantizer and Swing]==] [==[Diagnostics performance and audio]==] [==[OSC RT-safe messaging]==])
